server.port=8080

# The connection looks for environment variables on each of our PC
spring.datasource.url=jdbc:mysql://localhost:3306/freeroom_db
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Auto-create tables based on Java code
spring.jpa.hibernate.ddl-auto=update